apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 80         # Cluster port
      targetPort: 9090 # Prometheus container port
      nodePort: 31999  # Local machine port
