apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-deployment
  labels:
    app: telemetry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
    spec:
      containers:
        - name: telemetry-service
          image: telemetry-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080


