apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
spec:
  type: NodePort
  selector:
    app: telemetry-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080


